export const SIGN_IN = '/signin';
export const LANDING = '/landing';
export const SIGN_UP = '/signup';
export const SELETIVA = '/seletiva';
export const HOME = '/home';
export const ACCOUNT = '/account';
export const MEDIA = '/medias';
export const SERVICE = '/services'
export const FACULDADE = '/faculdade';
export const EDUCACAO ='/educacao';
export const VISTO = '/visto';
export const SOBRE = '/sobre';
export const FRANQUIA = '/franquia';
export const PASSWORD_FORGET = '/pw-forget';
export const ADMIN = '/admin';
export const ADMIN_DETAILS = '/admin/:id';
